---
- import_tasks: include-vars.yml

- import_tasks: install-with-package.yml
  when: not certbot_install_from_source

- import_tasks: install-from-source.yml
  when: certbot_install_from_source

- include_tasks: create-cert-standalone.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'standalone'
  loop_control:
    loop_var: cert_item

- include: systemd.yml
  when:
    - certbot_auto_renew
    - certbot_auto_renew_systemd

- import_tasks: renew-cron.yml
  when:
    - certbot_auto_renew
    - not certbot_auto_renew_systemd
